### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1040]
Remaining to get this out:
- [x] Pushed a test package of `v0.2.0-pre` - will download on windows box and make sure it runs - just for a sanity check since appveyor is kapoot tonight
- [x] Anything more to add to https://github.com/mapbox/mapbox-studio/issues/1012?
- [x] bump package.json, etc and follow https://github.com/mapbox/mapbox-studio/blob/mb-pages/CONTRIBUTING.md#tagging--releasing - #1042

Followups:
- [x] closeup #976, #974, and #969
- [x] ping on #850 to try testing again because app is now 64 bit
- [x] ping on #878 because atom-shell is now upgraded

**Comment by springmeyer** [comment]
done and available at https://www.mapbox.com/mapbox-studio
